language: python
sudo: required
dist: trusty
matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp27-cp27mu-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp35-cp35m-linux_x86_64.whl; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-linux_x86_64.whl; fi
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
script:
  - pycodestyle .
  - flake8 .
  - python setup.py install
  - python setup.py test
after_success:
  - codecov
notifications:
  email: false
